### ISSUE TITLE
Plugin causing error 500

### ISSUE THREAD

**Issue by shinsim** [MatthewC/yourls-password-protection#11]
Hi Matthew,

I'm having the same problem as described previously:
[https://github.com/MatthewC/yourls-password-protection/issues/2](url)

I'm using YOURLS v1.8.2
and Password-Protection v1.1

does this plugin only works on YOURLS v1.7.3 ?

**Comment by MatthewC** [comment]
Hello!
I've just tested the plugin on YOURLS v1.8.2, and haven't been able to recreate the error. Could you try looking through your error logs and seeing what exactly is causing it?
