### ISSUE TITLE
Password Delete

### ISSUE THREAD

**Issue by Ach1m9** [MatthewC/yourls-password-protection#12]
Hello Matthew,

thirst of all, thanks for the plugin ;) but if I delete a Short-URL, the password still exists in the DB. U should delete it in Database too.

Best Regards
Achim

**Comment by MatthewC** [comment]
Hi Achim,

Sorry for the delayed response, I will look into it, but feel free to submit a pull request!

(Edit 26/04/22: Still haven't gotten around to doing it, but I promise I haven't forgotten!)

Kind regards,
Matthew
