### ISSUE TITLE
Fatal Error after YOURLS 1.9 update.

### ISSUE THREAD

**Issue by SophiaAtkinson** [MatthewC/yourls-password-protection#13]
This is the following error.

`Fatal error: Uncaught BadMethodCallException: Class 'YOURLS\Database\YDB' does not have a method 'get_results' in /includes/vendor/aura/sql/src/AbstractExtendedPdo.php:113 Stack trace: #0 /user/plugins/yourls-password-protection/plugin.php(232): Aura\Sql\AbstractExtendedPdo->__call() #1 /user/plugins/yourls-password-protection/plugin.php(208): matthew_pwprotection_process_display() #2 /includes/functions-plugins.php(819): matthew_pwprotection_display_page() #3 /admin/plugins.php(8): yourls_plugin_admin_page() #4 {main} thrown in /includes/vendor/aura/sql/src/AbstractExtendedPdo.php on line 113`

I rolled back to 1.8.2 and the error stopped happening so something changed in the most recent update to cause this plugin to stop working. Hope this information helps, have a good day!

**Comment by MatthewC** [comment]
Hmm, I guess something might've changed with thew new YOURLS. I'm quite busy at the moment, but i should be able to update it within the next two weeks hopefully!
