### ISSUE TITLE
installed and activated, but not asking for a password

### ISSUE THREAD

**Issue by hernanpopper** [MatthewC/yourls-password-protection#17]
I've installed and activated the plugin, set up a password for a redirect, but it does not ask for it, it just redirects as if the plugin is not there.

![image](https://user-images.githubusercontent.com/104868017/212922174-3b79acae-ddd5-4c41-b50e-4b490c7a77f9.png)

It is live at p3.ar/yourls

Any advise?

**Comment by MatthewC** [comment]
Can I ask if you have other plugins installed, and what version of YOURLS you are using?

**Comment by hernanpopper** [comment]
Absolutely!

Version: 1.9.1


[image: image.png]

Based on your question, I deactivated GoogleTagManager and it works now...
Is that a requirement?

Thanks!

**Comment by MatthewC** [comment]
That could be the issue. I'll take a look at that plugin and see if it could cause an issue!

*Edit:* Yea, GTM seems to be the issue. They also edit the pre-redirect, and handle the redirection themselves. The way I see, i can either add support for adding a Google Tag or you could modify my `plugin.php' with similar code to that found in the other plugin.
