### ISSUE TITLE
Plugin causing HTTP Error 500

### ISSUE THREAD

**Issue by CharlesMagnuson** [MatthewC/yourls-password-protection#2]
Suddenly maybe 1-2 weeks ago, my Yourls started giving me 500 errors when I attempted to navigate to them. After troubleshooting, I've found that this plugin appears to be the culprit.

With the plugin disabled, all of my Yourls redirect without issue. When I then enable the plugin, I immediately see a 500 error. Refreshing the page clears the 500 error and I can again navigate to any of the Yourls I had navigated to previously before enabling the plugin. However, if I attempt to navigate to any new Yourls or any pre-existing Yourls which I had not visited before enabling the plugin, I will consistently see a 500 error. Disabling this plugin fixes the issue and allows the redirect to happen successfully.

Additionally, when I navigate to the plugin's settings page with the plugin enabled, it appears that there are missing settings. Nothing appears except column titles.

Here is a screencast where I reproduce the issue: http://ca.mag.cm/02f8f3290346

I'm running Yourls v1.7.3

I'm not very technically skilled so I don't really know how to investigate further. However, I figured I would report this situation in case it is of any use. Let me know if I've forgotten to include any details.

**Comment by MatthewC** [comment]
Hello! I wanted to ask if you've been getting these errors as soon as you installed the plugin, or if these issues started happening a while after installing the plugin. If the latter, have you done anything major which might have affected the plugin? (i.e updating YOURLS?)

**Comment by CharlesMagnuson** [comment]
Great question. I've had this plugin installed for many months, probably since the time I first setup my instance of YOURLS around 2 years ago. Everything was working fine until about January when I started to see these 500 errors.

To my knowledge, I have not done anything to modify my YOURLS instance in the last year. I have not performed any actions other than creating new short URLS. However, I notice that YOURLS released a new version, v1.7.3, on January 7th, almost exactly the date that this issue began: https://github.com/YOURLS/YOURLS/releases.

While I did not take any manual action to update my YOURLS instance, it appears that my instance was automatically upgraded to 1.7.3. My suspicion is that this new version of YOURLS is causing the plugin to not work correctly, but I'm not knowledgeable enough to state that definitively.

**Comment by MatthewC** [comment]
Can you double check that the current version of the plugin you have installed is the most recent one. There was a modified version sent out 7 months ago, just wanted to check if you have the most recent one, or if you still have the older version.

**Comment by CharlesMagnuson** [comment]
I currently have v1.1 of the YOURLSs Password Protection plugin installed.

**Comment by MatthewC** [comment]
I see. I haven't been able to reproduce the issue on my end. I'm going to have to ask that you take a look at the Troubleshooting Tips on the YOURLS GitHub page (found [here](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps#check-server-logs)). Try monitoring these files and attempt to recreate the issue, this will ensure that the most recent error is the one related to the issue you are experiencing. 

If possible, please upload the file (or at least the lines relating to the issue) here, so that I can assist you further.

**Comment by CharlesMagnuson** [comment]
Alrighty, thank you for looking into this with me. I will report back if I uncover useful information.

**Comment by MatthewC** [comment]
Hello! I wanted to check if you've made any progressing in searching for the issue.

**Comment by CharlesMagnuson** [comment]
Unfortunately I cannot locate any server logs. My server doesn't seem to have any of the suggested locations listed in that troubleshooting article. I apologize for being unable to provide further info.

**Comment by MatthewC** [comment]
Have you tried looking at the location of your apache logs for your specific operating system? For example, [this](https://unix.stackexchange.com/questions/38978/where-are-apache-file-access-logs-stored)?

**Comment by LenKiMo** [comment]
I met the 500 Error too and disable the plugin would avoid it. The bug appears when I upgeade to 1.7.3. And here is the server error log I found:

```
[Sat May 25 10:16:36.350148 2019] [php7:error] [pid 11687] [client ] PHP Fatal error:  require(): Failed opening required '/home/admin/web/[DomainHere]/public_html/includes/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/admin/web/[DomainHere]/public_html/includes/load-yourls.php on line 8
[Sat May 25 10:26:19.613322 2019] [php7:error] [pid 28835] [client ] PHP Fatal error:  Uncaught Error: Cannot access protected property YOURLS\\Database\\YDB::$option in /home/admin/web/[DomainHere]/public_html/user/plugins/yourls-password-protection/plugin.php:30\nStack trace:\n#0 /home/admin/web/[DomainHere]/public_html/includes/functions-plugins.php(152): warning_redirection(Array)\n#1 /home/admin/web/[DomainHere]/public_html/includes/functions-plugins.php(191): yourls_apply_filter('pre_redirect', Array)\n#2 /home/admin/web/[DomainHere]/public_html/includes/functions.php(709): yourls_do_action('pre_redirect', 'https://[DomainHere]', 302)\n#3 /home/admin/web/[DomainHere]/public_html/yourls-loader.php(65): yourls_redirect('https://[DomainHere]', 302)\n#4 {main}\n  thrown in /home/admin/web/[DomainHere]/public_html/user/plugins/yourls-password-protection/plugin.php on line 30
```

**Comment by MatthewC** [comment]
Just to confirm, when you had v1.7.2, the plugin worked perfectly, it wasn't until you updated to 1.7.3 that it began to fail, right? Or did you just do a fresh install of v1.7.3?

**Comment by LenKiMo** [comment]
Tough I had a long time doesn't use it, I can't confirm it clearly, but yes, it should works right when 1.7.2.
And the other thing is, the 500 Error also appears in admin interface, just like disable the plugin, it will meets 500 error at first then refresh the page would reload successfully, and the plugin has been disabled.

**Comment by MatthewC** [comment]
When did you install the plugin? Could you send me your current `plugin.php` file?

**Comment by LenKiMo** [comment]
Base on the server time record, I installed the plugin in Dec 1, 2017. Oh it actually quite old....

The plugin you can find it in here: https://mol.uno/opendownload/plugin.php

Hope I had not done any change cause error.

**Comment by MatthewC** [comment]
I can't seem to download the file, however, based on the date the plugin was installed, I believe I have solved the issue. @CharlesMagnuson @LenKiMo - I believe both of you have the outdated version of the plugin installed. If you install the latest version you should see the plugin start to work again.

Please update me on if this fixes your problem.

**Comment by LenKiMo** [comment]
It since like everything back to all right. I tried some links and all of them work properly.
I will keep eyes on it if there is any other problem. Thanks for your information.

**Comment by MatthewC** [comment]
No problem!

**Comment by MatthewC** [comment]
I also did a quick update to the login screen, if you re-install the `plugin.php` file, you'll see the updated login screen! If you like the current one, you are free to keep the current version.
