### ISSUE TITLE
Can't submit password

### ISSUE THREAD

**Issue by cloopadoop** [MatthewC/yourls-password-protection#22]
![image](https://github.com/MatthewC/yourls-password-protection/assets/1791012/0c6631ef-ae9d-412d-bbb1-1567590f2d18)

Clicking submit doesn't do anything--not even a console error 😭

I'm on YOURLs 1.9.2.

**Comment by MatthewC** [comment]
Hi, do you get any error if you do the following:
1. Open the developer console (usually `F12`)
2. Hit Ctrl+F5 (or the equivalent shortcut to force refresh the website)

Specifically, any jQuery error?

~Apart from that, I'll try loading up version 1.9.2 of YOURLS and seeing if I can re-create it on my end~. I wasn't able to re-create this on my end, any luck on your side?

**Comment by cloopadoop** [comment]
Ope sorry bud I didn't get these notifications! I tried again just now and was not able to recreate my own issue so... I guess we're good. Thanks for lookin'. :) Nice plugin!

**Comment by MatthewC** [comment]
No problem! I'm glad you enjoy the plugin :D

If the problem ever arises again, don't hesitate to create a new issue.

Have a great day!
