### ISSUE TITLE
Display or Retrieve Passwords in Plain Text

### ISSUE THREAD

**Issue by mike14-2** [MatthewC/yourls-password-protection#25]
Hello,

I would like to know if it is possible to display or retrieve passwords in plain text. I would prefer not to have to change the passwords later if I haven’t written them down somewhere else. Or is the intention that they should be written down separately?

Thank you very much.

**Comment by MatthewC** [comment]
Hello! The passwords are hashed, so I'm afraid this is not possible

If you ever forget the password, you can always overwrite it using the Admin page.
