### ISSUE TITLE
Text and border not visible in password dialog

### ISSUE THREAD

**Issue by tjndr** [MatthewC/yourls-password-protection#3]
Please see the attached file
![PP_Area_Snip](https://user-images.githubusercontent.com/12607177/62647043-aaaa7a00-b91d-11e9-9840-e288818343a9.png)

I only changed the colors, but in the main PHP file, I am not able to figure it out that why any text or border is not showing. Moreover, entering wrong password does not throw any error popup or warning.

**Comment by MatthewC** [comment]
Hello! The “no error message” part of your issue is actually a mistake I made with the code, I’ll fix it as soon as possible. Although, what do you mean by “no borders” and “no text”? What exactly are you comparing it to?

**Comment by tjndr** [comment]
Sorry for the late reply, I meant text or border around password box. I can see the text “Enter your password” or something similar in the code but it doesn’t show up on the webpage. In my original message I attached a picture, which shows only password entry box and a button, I am not able to get any custom text above that.

**Comment by MatthewC** [comment]
Hello again! I have fixed the error message not being displayed (#4), and just to confirm what you are saying, you are trying to get a message above the password box saying "Please enter password" or something like that, correct?

**Comment by MatthewC** [comment]
If it's adding a message above the password input box, simply insert right before the `<form>` tag, like so: 

```
<div id="login">
    <a style="color:orange;">Please enter password</a>
    <form method="post">
```
You should also be able to style it by altering the contents of the `style` attribute. Additionally, you can change the tag from an `a` to a `p` if you would like it to have a gap between the input box. Which would look like this:
![image](https://user-images.githubusercontent.com/16270955/63066713-50329000-bec0-11e9-912b-1c7dee8ee80a.png)

**Comment by MatthewC** [comment]
If you would like to add a border around the input box you can edit the `container` div, making it look something like this:
```
<div class="container" style="border: 1px solid white; padding-left: 20px; padding-right: 20px;">
```
I'd recommend ensuring the `padding-left` and `padding-right` are kept the same if you'd like the box to be centered, removing the padding makes the border seem really uncomfortable(?), although you could do it. The final result would look something like this:
![image](https://user-images.githubusercontent.com/16270955/63066895-35145000-bec1-11e9-868f-69357d5384e9.png)

**Comment by tjndr** [comment]
Thank you so much Matthew.
