### ISSUE TITLE
1.7.9 - does not work

### ISSUE THREAD

**Issue by nsrafk** [MatthewC/yourls-password-protection#5]
Hi. I can’t get plugin to work in current version. I’m using the docker image. I can set a password and enable it but it doesn’t follow through.

Any tips?

**Comment by MatthewC** [comment]
Let me see if I can re-create it on my side.

**Comment by nsrafk** [comment]
> Let me see if I can re-create it on my side.

Wow thats a quick response. Thank you a lot

**Comment by MatthewC** [comment]
No problem! Although I just updated my YOURLS to the latest version, and everything worked as intended (although I'm not using the docker image). Could you probably be a bit more specific as to what's not working?

**Comment by nsrafk** [comment]
Okay thats interesting. I'm using the latest docker image and a reverse proxy.

I install the plugin like any other with git clone, enable it in the tools menu of the admin interface, go to the settings area and pick a link and enter a password and make sure 'enabled' is checked in there.

How can i further assist to figure out why it is not working?

**Comment by MatthewC** [comment]
What happens after you set the password? Do you get an error? Does the link simply immediately redirect instead of prompting for a password?

**Comment by nsrafk** [comment]
Nothing happens - it all looks good but as you say the link will redirect without prompting for a password. 

https://link.dahl.vip/public has a pw of ‘test’ right now - as you can see it does not prompt :)

**Comment by MatthewC** [comment]
I see. If you give me some time, I'll spin up a docker image and see if I can re-create it there.

However, have you tried looking at any PHP log, or if docker says anything?

**Comment by nsrafk** [comment]
I can this from docker container log:

```
11; CrOS x86_64 13310.59.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.84 Safari/537.36"
[Tue Sep 29 09:39:09.021383 2020] [autoindex:error] [pid 28] [client 192.168.20.8:59378] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive
192.168.20.8 - - [29/Sep/2020:09:39:09 +0000] "GET / HTTP/1.1" 403 439 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
192.168.20.8 - - [29/Sep/2020:09:39:10 +0000] "GET /public HTTP/1.1" 200 418 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
192.168.20.8 - - [29/Sep/2020:09:39:45 +0000] "GET /admin/ HTTP/1.1" 200 3953 "https://REMOVED/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
```

The IP in context is the internal docker ip of my proxy so now i see that YOURLS doesn't respect the headers sent from my reverse proxy. Yikes. I'm by no means an expert in coding so dunno if you can use it for anything

**Comment by MatthewC** [comment]
Everything there seems fine, do you notice any difference before and after you try to access the URL with the password feature enabled? 

Additionally, can you confirm if any other plugin which alters redirection in any way is also working?

**Comment by nsrafk** [comment]
Okay thanks. This is weird. I just disable my other plugins and it now prompts for a pw. I’ve now enabled the other plugins one-by-one to see which one was the course. I have enabled all and it still works. 

Sorry to waste your time in this

**Comment by MatthewC** [comment]
No worries! Have a great day.
